---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://ikennaokpala.github.io"
title: "There is not traffic in the extra mile."
canonifyurls: true
